name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          # working_directory: source/
          args: -jobname=cv -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          compiler: latexmk

      - name: Upload pdf document
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: cv.pdf
# 
# name: Release Compiled PDF 
# on: push
# jobs:
#   test-example:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: antaljanosbenjamin/compile-latex@v1.0.0
#         with:
#           file: test.tex
#           args: -pdf
#       - run: '(test -f test.pdf && echo PDF exists) || (echo PDF does not exist && exit 1)'
